// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yssk22/hpapp/go/service/ent/auth"
	"github.com/yssk22/hpapp/go/service/ent/user"
)

// AuthCreate is the builder for creating a Auth entity.
type AuthCreate struct {
	config
	mutation *AuthMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ac *AuthCreate) SetCreatedAt(t time.Time) *AuthCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AuthCreate) SetNillableCreatedAt(t *time.Time) *AuthCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AuthCreate) SetUpdatedAt(t time.Time) *AuthCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AuthCreate) SetNillableUpdatedAt(t *time.Time) *AuthCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetProviderName sets the "provider_name" field.
func (ac *AuthCreate) SetProviderName(s string) *AuthCreate {
	ac.mutation.SetProviderName(s)
	return ac
}

// SetProviderUserID sets the "provider_user_id" field.
func (ac *AuthCreate) SetProviderUserID(s string) *AuthCreate {
	ac.mutation.SetProviderUserID(s)
	return ac
}

// SetAccessToken sets the "access_token" field.
func (ac *AuthCreate) SetAccessToken(s string) *AuthCreate {
	ac.mutation.SetAccessToken(s)
	return ac
}

// SetRefreshToken sets the "refresh_token" field.
func (ac *AuthCreate) SetRefreshToken(s string) *AuthCreate {
	ac.mutation.SetRefreshToken(s)
	return ac
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (ac *AuthCreate) SetNillableRefreshToken(s *string) *AuthCreate {
	if s != nil {
		ac.SetRefreshToken(*s)
	}
	return ac
}

// SetExpireAt sets the "expire_at" field.
func (ac *AuthCreate) SetExpireAt(t time.Time) *AuthCreate {
	ac.mutation.SetExpireAt(t)
	return ac
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (ac *AuthCreate) SetNillableExpireAt(t *time.Time) *AuthCreate {
	if t != nil {
		ac.SetExpireAt(*t)
	}
	return ac
}

// SetScope sets the "scope" field.
func (ac *AuthCreate) SetScope(s []string) *AuthCreate {
	ac.mutation.SetScope(s)
	return ac
}

// SetOwnerUserID sets the "owner_user_id" field.
func (ac *AuthCreate) SetOwnerUserID(i int) *AuthCreate {
	ac.mutation.SetOwnerUserID(i)
	return ac
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (ac *AuthCreate) SetNillableOwnerUserID(i *int) *AuthCreate {
	if i != nil {
		ac.SetOwnerUserID(*i)
	}
	return ac
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ac *AuthCreate) SetUserID(id int) *AuthCreate {
	ac.mutation.SetUserID(id)
	return ac
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (ac *AuthCreate) SetNillableUserID(id *int) *AuthCreate {
	if id != nil {
		ac = ac.SetUserID(*id)
	}
	return ac
}

// SetUser sets the "user" edge to the User entity.
func (ac *AuthCreate) SetUser(u *User) *AuthCreate {
	return ac.SetUserID(u.ID)
}

// Mutation returns the AuthMutation object of the builder.
func (ac *AuthCreate) Mutation() *AuthMutation {
	return ac.mutation
}

// Save creates the Auth in the database.
func (ac *AuthCreate) Save(ctx context.Context) (*Auth, error) {
	return withHooks[*Auth, AuthMutation](ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AuthCreate) SaveX(ctx context.Context) *Auth {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AuthCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AuthCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AuthCreate) check() error {
	if _, ok := ac.mutation.ProviderName(); !ok {
		return &ValidationError{Name: "provider_name", err: errors.New(`ent: missing required field "Auth.provider_name"`)}
	}
	if _, ok := ac.mutation.ProviderUserID(); !ok {
		return &ValidationError{Name: "provider_user_id", err: errors.New(`ent: missing required field "Auth.provider_user_id"`)}
	}
	if _, ok := ac.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "Auth.access_token"`)}
	}
	return nil
}

func (ac *AuthCreate) sqlSave(ctx context.Context) (*Auth, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AuthCreate) createSpec() (*Auth, *sqlgraph.CreateSpec) {
	var (
		_node = &Auth{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(auth.Table, sqlgraph.NewFieldSpec(auth.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ac.conflict
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(auth.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(auth.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.ProviderName(); ok {
		_spec.SetField(auth.FieldProviderName, field.TypeString, value)
		_node.ProviderName = value
	}
	if value, ok := ac.mutation.ProviderUserID(); ok {
		_spec.SetField(auth.FieldProviderUserID, field.TypeString, value)
		_node.ProviderUserID = value
	}
	if value, ok := ac.mutation.AccessToken(); ok {
		_spec.SetField(auth.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := ac.mutation.RefreshToken(); ok {
		_spec.SetField(auth.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := ac.mutation.ExpireAt(); ok {
		_spec.SetField(auth.FieldExpireAt, field.TypeTime, value)
		_node.ExpireAt = value
	}
	if value, ok := ac.mutation.Scope(); ok {
		_spec.SetField(auth.FieldScope, field.TypeJSON, value)
		_node.Scope = value
	}
	if nodes := ac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auth.UserTable,
			Columns: []string{auth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Auth.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ac *AuthCreate) OnConflict(opts ...sql.ConflictOption) *AuthUpsertOne {
	ac.conflict = opts
	return &AuthUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Auth.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *AuthCreate) OnConflictColumns(columns ...string) *AuthUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &AuthUpsertOne{
		create: ac,
	}
}

type (
	// AuthUpsertOne is the builder for "upsert"-ing
	//  one Auth node.
	AuthUpsertOne struct {
		create *AuthCreate
	}

	// AuthUpsert is the "OnConflict" setter.
	AuthUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthUpsert) SetUpdatedAt(v time.Time) *AuthUpsert {
	u.Set(auth.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthUpsert) UpdateUpdatedAt() *AuthUpsert {
	u.SetExcluded(auth.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AuthUpsert) ClearUpdatedAt() *AuthUpsert {
	u.SetNull(auth.FieldUpdatedAt)
	return u
}

// SetProviderName sets the "provider_name" field.
func (u *AuthUpsert) SetProviderName(v string) *AuthUpsert {
	u.Set(auth.FieldProviderName, v)
	return u
}

// UpdateProviderName sets the "provider_name" field to the value that was provided on create.
func (u *AuthUpsert) UpdateProviderName() *AuthUpsert {
	u.SetExcluded(auth.FieldProviderName)
	return u
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *AuthUpsert) SetProviderUserID(v string) *AuthUpsert {
	u.Set(auth.FieldProviderUserID, v)
	return u
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *AuthUpsert) UpdateProviderUserID() *AuthUpsert {
	u.SetExcluded(auth.FieldProviderUserID)
	return u
}

// SetAccessToken sets the "access_token" field.
func (u *AuthUpsert) SetAccessToken(v string) *AuthUpsert {
	u.Set(auth.FieldAccessToken, v)
	return u
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *AuthUpsert) UpdateAccessToken() *AuthUpsert {
	u.SetExcluded(auth.FieldAccessToken)
	return u
}

// SetRefreshToken sets the "refresh_token" field.
func (u *AuthUpsert) SetRefreshToken(v string) *AuthUpsert {
	u.Set(auth.FieldRefreshToken, v)
	return u
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *AuthUpsert) UpdateRefreshToken() *AuthUpsert {
	u.SetExcluded(auth.FieldRefreshToken)
	return u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (u *AuthUpsert) ClearRefreshToken() *AuthUpsert {
	u.SetNull(auth.FieldRefreshToken)
	return u
}

// SetExpireAt sets the "expire_at" field.
func (u *AuthUpsert) SetExpireAt(v time.Time) *AuthUpsert {
	u.Set(auth.FieldExpireAt, v)
	return u
}

// UpdateExpireAt sets the "expire_at" field to the value that was provided on create.
func (u *AuthUpsert) UpdateExpireAt() *AuthUpsert {
	u.SetExcluded(auth.FieldExpireAt)
	return u
}

// ClearExpireAt clears the value of the "expire_at" field.
func (u *AuthUpsert) ClearExpireAt() *AuthUpsert {
	u.SetNull(auth.FieldExpireAt)
	return u
}

// SetScope sets the "scope" field.
func (u *AuthUpsert) SetScope(v []string) *AuthUpsert {
	u.Set(auth.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *AuthUpsert) UpdateScope() *AuthUpsert {
	u.SetExcluded(auth.FieldScope)
	return u
}

// ClearScope clears the value of the "scope" field.
func (u *AuthUpsert) ClearScope() *AuthUpsert {
	u.SetNull(auth.FieldScope)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *AuthUpsert) SetOwnerUserID(v int) *AuthUpsert {
	u.Set(auth.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *AuthUpsert) UpdateOwnerUserID() *AuthUpsert {
	u.SetExcluded(auth.FieldOwnerUserID)
	return u
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *AuthUpsert) ClearOwnerUserID() *AuthUpsert {
	u.SetNull(auth.FieldOwnerUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Auth.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthUpsertOne) UpdateNewValues() *AuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(auth.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Auth.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthUpsertOne) Ignore() *AuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthUpsertOne) DoNothing() *AuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthCreate.OnConflict
// documentation for more info.
func (u *AuthUpsertOne) Update(set func(*AuthUpsert)) *AuthUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthUpsertOne) SetUpdatedAt(v time.Time) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateUpdatedAt() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AuthUpsertOne) ClearUpdatedAt() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetProviderName sets the "provider_name" field.
func (u *AuthUpsertOne) SetProviderName(v string) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetProviderName(v)
	})
}

// UpdateProviderName sets the "provider_name" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateProviderName() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateProviderName()
	})
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *AuthUpsertOne) SetProviderUserID(v string) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetProviderUserID(v)
	})
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateProviderUserID() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateProviderUserID()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *AuthUpsertOne) SetAccessToken(v string) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateAccessToken() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateAccessToken()
	})
}

// SetRefreshToken sets the "refresh_token" field.
func (u *AuthUpsertOne) SetRefreshToken(v string) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetRefreshToken(v)
	})
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateRefreshToken() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateRefreshToken()
	})
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (u *AuthUpsertOne) ClearRefreshToken() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.ClearRefreshToken()
	})
}

// SetExpireAt sets the "expire_at" field.
func (u *AuthUpsertOne) SetExpireAt(v time.Time) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetExpireAt(v)
	})
}

// UpdateExpireAt sets the "expire_at" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateExpireAt() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateExpireAt()
	})
}

// ClearExpireAt clears the value of the "expire_at" field.
func (u *AuthUpsertOne) ClearExpireAt() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.ClearExpireAt()
	})
}

// SetScope sets the "scope" field.
func (u *AuthUpsertOne) SetScope(v []string) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateScope() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *AuthUpsertOne) ClearScope() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.ClearScope()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *AuthUpsertOne) SetOwnerUserID(v int) *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *AuthUpsertOne) UpdateOwnerUserID() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *AuthUpsertOne) ClearOwnerUserID() *AuthUpsertOne {
	return u.Update(func(s *AuthUpsert) {
		s.ClearOwnerUserID()
	})
}

// Exec executes the query.
func (u *AuthUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthCreateBulk is the builder for creating many Auth entities in bulk.
type AuthCreateBulk struct {
	config
	builders []*AuthCreate
	conflict []sql.ConflictOption
}

// Save creates the Auth entities in the database.
func (acb *AuthCreateBulk) Save(ctx context.Context) ([]*Auth, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Auth, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AuthCreateBulk) SaveX(ctx context.Context) []*Auth {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AuthCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AuthCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Auth.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (acb *AuthCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthUpsertBulk {
	acb.conflict = opts
	return &AuthUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Auth.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *AuthCreateBulk) OnConflictColumns(columns ...string) *AuthUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &AuthUpsertBulk{
		create: acb,
	}
}

// AuthUpsertBulk is the builder for "upsert"-ing
// a bulk of Auth nodes.
type AuthUpsertBulk struct {
	create *AuthCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Auth.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthUpsertBulk) UpdateNewValues() *AuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(auth.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Auth.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthUpsertBulk) Ignore() *AuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthUpsertBulk) DoNothing() *AuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthCreateBulk.OnConflict
// documentation for more info.
func (u *AuthUpsertBulk) Update(set func(*AuthUpsert)) *AuthUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthUpsertBulk) SetUpdatedAt(v time.Time) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateUpdatedAt() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *AuthUpsertBulk) ClearUpdatedAt() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetProviderName sets the "provider_name" field.
func (u *AuthUpsertBulk) SetProviderName(v string) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetProviderName(v)
	})
}

// UpdateProviderName sets the "provider_name" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateProviderName() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateProviderName()
	})
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *AuthUpsertBulk) SetProviderUserID(v string) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetProviderUserID(v)
	})
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateProviderUserID() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateProviderUserID()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *AuthUpsertBulk) SetAccessToken(v string) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateAccessToken() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateAccessToken()
	})
}

// SetRefreshToken sets the "refresh_token" field.
func (u *AuthUpsertBulk) SetRefreshToken(v string) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetRefreshToken(v)
	})
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateRefreshToken() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateRefreshToken()
	})
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (u *AuthUpsertBulk) ClearRefreshToken() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.ClearRefreshToken()
	})
}

// SetExpireAt sets the "expire_at" field.
func (u *AuthUpsertBulk) SetExpireAt(v time.Time) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetExpireAt(v)
	})
}

// UpdateExpireAt sets the "expire_at" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateExpireAt() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateExpireAt()
	})
}

// ClearExpireAt clears the value of the "expire_at" field.
func (u *AuthUpsertBulk) ClearExpireAt() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.ClearExpireAt()
	})
}

// SetScope sets the "scope" field.
func (u *AuthUpsertBulk) SetScope(v []string) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateScope() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *AuthUpsertBulk) ClearScope() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.ClearScope()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *AuthUpsertBulk) SetOwnerUserID(v int) *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *AuthUpsertBulk) UpdateOwnerUserID() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.UpdateOwnerUserID()
	})
}

// ClearOwnerUserID clears the value of the "owner_user_id" field.
func (u *AuthUpsertBulk) ClearOwnerUserID() *AuthUpsertBulk {
	return u.Update(func(s *AuthUpsert) {
		s.ClearOwnerUserID()
	})
}

// Exec executes the query.
func (u *AuthUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
