// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yssk22/hpapp/go/service/ent/hpasset"
	"github.com/yssk22/hpapp/go/service/ent/predicate"
)

// HPAssetDelete is the builder for deleting a HPAsset entity.
type HPAssetDelete struct {
	config
	hooks    []Hook
	mutation *HPAssetMutation
}

// Where appends a list predicates to the HPAssetDelete builder.
func (had *HPAssetDelete) Where(ps ...predicate.HPAsset) *HPAssetDelete {
	had.mutation.Where(ps...)
	return had
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (had *HPAssetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, HPAssetMutation](ctx, had.sqlExec, had.mutation, had.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (had *HPAssetDelete) ExecX(ctx context.Context) int {
	n, err := had.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (had *HPAssetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(hpasset.Table, sqlgraph.NewFieldSpec(hpasset.FieldID, field.TypeInt))
	if ps := had.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, had.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	had.mutation.done = true
	return affected, err
}

// HPAssetDeleteOne is the builder for deleting a single HPAsset entity.
type HPAssetDeleteOne struct {
	had *HPAssetDelete
}

// Where appends a list predicates to the HPAssetDelete builder.
func (hado *HPAssetDeleteOne) Where(ps ...predicate.HPAsset) *HPAssetDeleteOne {
	hado.had.mutation.Where(ps...)
	return hado
}

// Exec executes the deletion query.
func (hado *HPAssetDeleteOne) Exec(ctx context.Context) error {
	n, err := hado.had.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{hpasset.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hado *HPAssetDeleteOne) ExecX(ctx context.Context) {
	if err := hado.Exec(ctx); err != nil {
		panic(err)
	}
}
