// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"hpapp.yssk22.dev/go/service/ent/hpfeeditem"
	"hpapp.yssk22.dev/go/service/ent/hpviewhistory"
	"hpapp.yssk22.dev/go/service/ent/predicate"
	"hpapp.yssk22.dev/go/service/ent/user"
)

// HPViewHistoryQuery is the builder for querying HPViewHistory entities.
type HPViewHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []hpviewhistory.Order
	inters     []Interceptor
	predicates []predicate.HPViewHistory
	withFeed   *HPFeedItemQuery
	withUser   *UserQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*HPViewHistory) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HPViewHistoryQuery builder.
func (hvhq *HPViewHistoryQuery) Where(ps ...predicate.HPViewHistory) *HPViewHistoryQuery {
	hvhq.predicates = append(hvhq.predicates, ps...)
	return hvhq
}

// Limit the number of records to be returned by this query.
func (hvhq *HPViewHistoryQuery) Limit(limit int) *HPViewHistoryQuery {
	hvhq.ctx.Limit = &limit
	return hvhq
}

// Offset to start from.
func (hvhq *HPViewHistoryQuery) Offset(offset int) *HPViewHistoryQuery {
	hvhq.ctx.Offset = &offset
	return hvhq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hvhq *HPViewHistoryQuery) Unique(unique bool) *HPViewHistoryQuery {
	hvhq.ctx.Unique = &unique
	return hvhq
}

// Order specifies how the records should be ordered.
func (hvhq *HPViewHistoryQuery) Order(o ...hpviewhistory.Order) *HPViewHistoryQuery {
	hvhq.order = append(hvhq.order, o...)
	return hvhq
}

// QueryFeed chains the current query on the "feed" edge.
func (hvhq *HPViewHistoryQuery) QueryFeed() *HPFeedItemQuery {
	query := (&HPFeedItemClient{config: hvhq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hvhq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hvhq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hpviewhistory.Table, hpviewhistory.FieldID, selector),
			sqlgraph.To(hpfeeditem.Table, hpfeeditem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, hpviewhistory.FeedTable, hpviewhistory.FeedColumn),
		)
		fromU = sqlgraph.SetNeighbors(hvhq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (hvhq *HPViewHistoryQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: hvhq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hvhq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hvhq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hpviewhistory.Table, hpviewhistory.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, hpviewhistory.UserTable, hpviewhistory.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(hvhq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HPViewHistory entity from the query.
// Returns a *NotFoundError when no HPViewHistory was found.
func (hvhq *HPViewHistoryQuery) First(ctx context.Context) (*HPViewHistory, error) {
	nodes, err := hvhq.Limit(1).All(setContextOp(ctx, hvhq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hpviewhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) FirstX(ctx context.Context) *HPViewHistory {
	node, err := hvhq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HPViewHistory ID from the query.
// Returns a *NotFoundError when no HPViewHistory ID was found.
func (hvhq *HPViewHistoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hvhq.Limit(1).IDs(setContextOp(ctx, hvhq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hpviewhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) FirstIDX(ctx context.Context) int {
	id, err := hvhq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HPViewHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HPViewHistory entity is found.
// Returns a *NotFoundError when no HPViewHistory entities are found.
func (hvhq *HPViewHistoryQuery) Only(ctx context.Context) (*HPViewHistory, error) {
	nodes, err := hvhq.Limit(2).All(setContextOp(ctx, hvhq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hpviewhistory.Label}
	default:
		return nil, &NotSingularError{hpviewhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) OnlyX(ctx context.Context) *HPViewHistory {
	node, err := hvhq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HPViewHistory ID in the query.
// Returns a *NotSingularError when more than one HPViewHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (hvhq *HPViewHistoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hvhq.Limit(2).IDs(setContextOp(ctx, hvhq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hpviewhistory.Label}
	default:
		err = &NotSingularError{hpviewhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := hvhq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HPViewHistories.
func (hvhq *HPViewHistoryQuery) All(ctx context.Context) ([]*HPViewHistory, error) {
	ctx = setContextOp(ctx, hvhq.ctx, "All")
	if err := hvhq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HPViewHistory, *HPViewHistoryQuery]()
	return withInterceptors[[]*HPViewHistory](ctx, hvhq, qr, hvhq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) AllX(ctx context.Context) []*HPViewHistory {
	nodes, err := hvhq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HPViewHistory IDs.
func (hvhq *HPViewHistoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hvhq.ctx.Unique == nil && hvhq.path != nil {
		hvhq.Unique(true)
	}
	ctx = setContextOp(ctx, hvhq.ctx, "IDs")
	if err = hvhq.Select(hpviewhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) IDsX(ctx context.Context) []int {
	ids, err := hvhq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hvhq *HPViewHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hvhq.ctx, "Count")
	if err := hvhq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hvhq, querierCount[*HPViewHistoryQuery](), hvhq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) CountX(ctx context.Context) int {
	count, err := hvhq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hvhq *HPViewHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hvhq.ctx, "Exist")
	switch _, err := hvhq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hvhq *HPViewHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := hvhq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HPViewHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hvhq *HPViewHistoryQuery) Clone() *HPViewHistoryQuery {
	if hvhq == nil {
		return nil
	}
	return &HPViewHistoryQuery{
		config:     hvhq.config,
		ctx:        hvhq.ctx.Clone(),
		order:      append([]hpviewhistory.Order{}, hvhq.order...),
		inters:     append([]Interceptor{}, hvhq.inters...),
		predicates: append([]predicate.HPViewHistory{}, hvhq.predicates...),
		withFeed:   hvhq.withFeed.Clone(),
		withUser:   hvhq.withUser.Clone(),
		// clone intermediate query.
		sql:  hvhq.sql.Clone(),
		path: hvhq.path,
	}
}

// WithFeed tells the query-builder to eager-load the nodes that are connected to
// the "feed" edge. The optional arguments are used to configure the query builder of the edge.
func (hvhq *HPViewHistoryQuery) WithFeed(opts ...func(*HPFeedItemQuery)) *HPViewHistoryQuery {
	query := (&HPFeedItemClient{config: hvhq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hvhq.withFeed = query
	return hvhq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (hvhq *HPViewHistoryQuery) WithUser(opts ...func(*UserQuery)) *HPViewHistoryQuery {
	query := (&UserClient{config: hvhq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hvhq.withUser = query
	return hvhq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HPViewHistory.Query().
//		GroupBy(hpviewhistory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (hvhq *HPViewHistoryQuery) GroupBy(field string, fields ...string) *HPViewHistoryGroupBy {
	hvhq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HPViewHistoryGroupBy{build: hvhq}
	grbuild.flds = &hvhq.ctx.Fields
	grbuild.label = hpviewhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.HPViewHistory.Query().
//		Select(hpviewhistory.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (hvhq *HPViewHistoryQuery) Select(fields ...string) *HPViewHistorySelect {
	hvhq.ctx.Fields = append(hvhq.ctx.Fields, fields...)
	sbuild := &HPViewHistorySelect{HPViewHistoryQuery: hvhq}
	sbuild.label = hpviewhistory.Label
	sbuild.flds, sbuild.scan = &hvhq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HPViewHistorySelect configured with the given aggregations.
func (hvhq *HPViewHistoryQuery) Aggregate(fns ...AggregateFunc) *HPViewHistorySelect {
	return hvhq.Select().Aggregate(fns...)
}

func (hvhq *HPViewHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hvhq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hvhq); err != nil {
				return err
			}
		}
	}
	for _, f := range hvhq.ctx.Fields {
		if !hpviewhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hvhq.path != nil {
		prev, err := hvhq.path(ctx)
		if err != nil {
			return err
		}
		hvhq.sql = prev
	}
	if hpviewhistory.Policy == nil {
		return errors.New("ent: uninitialized hpviewhistory.Policy (forgotten import ent/runtime?)")
	}
	if err := hpviewhistory.Policy.EvalQuery(ctx, hvhq); err != nil {
		return err
	}
	return nil
}

func (hvhq *HPViewHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HPViewHistory, error) {
	var (
		nodes       = []*HPViewHistory{}
		withFKs     = hvhq.withFKs
		_spec       = hvhq.querySpec()
		loadedTypes = [2]bool{
			hvhq.withFeed != nil,
			hvhq.withUser != nil,
		}
	)
	if hvhq.withFeed != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, hpviewhistory.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HPViewHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HPViewHistory{config: hvhq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(hvhq.modifiers) > 0 {
		_spec.Modifiers = hvhq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hvhq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hvhq.withFeed; query != nil {
		if err := hvhq.loadFeed(ctx, query, nodes, nil,
			func(n *HPViewHistory, e *HPFeedItem) { n.Edges.Feed = e }); err != nil {
			return nil, err
		}
	}
	if query := hvhq.withUser; query != nil {
		if err := hvhq.loadUser(ctx, query, nodes, nil,
			func(n *HPViewHistory, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	for i := range hvhq.loadTotal {
		if err := hvhq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hvhq *HPViewHistoryQuery) loadFeed(ctx context.Context, query *HPFeedItemQuery, nodes []*HPViewHistory, init func(*HPViewHistory), assign func(*HPViewHistory, *HPFeedItem)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HPViewHistory)
	for i := range nodes {
		if nodes[i].hp_feed_item_view_histories == nil {
			continue
		}
		fk := *nodes[i].hp_feed_item_view_histories
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(hpfeeditem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "hp_feed_item_view_histories" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (hvhq *HPViewHistoryQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*HPViewHistory, init func(*HPViewHistory), assign func(*HPViewHistory, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*HPViewHistory)
	for i := range nodes {
		fk := nodes[i].OwnerUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (hvhq *HPViewHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hvhq.querySpec()
	if len(hvhq.modifiers) > 0 {
		_spec.Modifiers = hvhq.modifiers
	}
	_spec.Node.Columns = hvhq.ctx.Fields
	if len(hvhq.ctx.Fields) > 0 {
		_spec.Unique = hvhq.ctx.Unique != nil && *hvhq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hvhq.driver, _spec)
}

func (hvhq *HPViewHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hpviewhistory.Table, hpviewhistory.Columns, sqlgraph.NewFieldSpec(hpviewhistory.FieldID, field.TypeInt))
	_spec.From = hvhq.sql
	if unique := hvhq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hvhq.path != nil {
		_spec.Unique = true
	}
	if fields := hvhq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hpviewhistory.FieldID)
		for i := range fields {
			if fields[i] != hpviewhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if hvhq.withUser != nil {
			_spec.Node.AddColumnOnce(hpviewhistory.FieldOwnerUserID)
		}
	}
	if ps := hvhq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hvhq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hvhq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hvhq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hvhq *HPViewHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hvhq.driver.Dialect())
	t1 := builder.Table(hpviewhistory.Table)
	columns := hvhq.ctx.Fields
	if len(columns) == 0 {
		columns = hpviewhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hvhq.sql != nil {
		selector = hvhq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hvhq.ctx.Unique != nil && *hvhq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hvhq.predicates {
		p(selector)
	}
	for _, p := range hvhq.order {
		p(selector)
	}
	if offset := hvhq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hvhq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HPViewHistoryGroupBy is the group-by builder for HPViewHistory entities.
type HPViewHistoryGroupBy struct {
	selector
	build *HPViewHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hvhgb *HPViewHistoryGroupBy) Aggregate(fns ...AggregateFunc) *HPViewHistoryGroupBy {
	hvhgb.fns = append(hvhgb.fns, fns...)
	return hvhgb
}

// Scan applies the selector query and scans the result into the given value.
func (hvhgb *HPViewHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hvhgb.build.ctx, "GroupBy")
	if err := hvhgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HPViewHistoryQuery, *HPViewHistoryGroupBy](ctx, hvhgb.build, hvhgb, hvhgb.build.inters, v)
}

func (hvhgb *HPViewHistoryGroupBy) sqlScan(ctx context.Context, root *HPViewHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hvhgb.fns))
	for _, fn := range hvhgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hvhgb.flds)+len(hvhgb.fns))
		for _, f := range *hvhgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hvhgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hvhgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HPViewHistorySelect is the builder for selecting fields of HPViewHistory entities.
type HPViewHistorySelect struct {
	*HPViewHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hvhs *HPViewHistorySelect) Aggregate(fns ...AggregateFunc) *HPViewHistorySelect {
	hvhs.fns = append(hvhs.fns, fns...)
	return hvhs
}

// Scan applies the selector query and scans the result into the given value.
func (hvhs *HPViewHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hvhs.ctx, "Select")
	if err := hvhs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HPViewHistoryQuery, *HPViewHistorySelect](ctx, hvhs.HPViewHistoryQuery, hvhs, hvhs.inters, v)
}

func (hvhs *HPViewHistorySelect) sqlScan(ctx context.Context, root *HPViewHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hvhs.fns))
	for _, fn := range hvhs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hvhs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hvhs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
