// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yssk22/hpapp/go/service/ent/metricdryrun"
	"github.com/yssk22/hpapp/go/service/ent/predicate"
)

// MetricDryRunDelete is the builder for deleting a MetricDryRun entity.
type MetricDryRunDelete struct {
	config
	hooks    []Hook
	mutation *MetricDryRunMutation
}

// Where appends a list predicates to the MetricDryRunDelete builder.
func (mdrd *MetricDryRunDelete) Where(ps ...predicate.MetricDryRun) *MetricDryRunDelete {
	mdrd.mutation.Where(ps...)
	return mdrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mdrd *MetricDryRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, MetricDryRunMutation](ctx, mdrd.sqlExec, mdrd.mutation, mdrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mdrd *MetricDryRunDelete) ExecX(ctx context.Context) int {
	n, err := mdrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mdrd *MetricDryRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(metricdryrun.Table, sqlgraph.NewFieldSpec(metricdryrun.FieldID, field.TypeInt))
	if ps := mdrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mdrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mdrd.mutation.done = true
	return affected, err
}

// MetricDryRunDeleteOne is the builder for deleting a single MetricDryRun entity.
type MetricDryRunDeleteOne struct {
	mdrd *MetricDryRunDelete
}

// Where appends a list predicates to the MetricDryRunDelete builder.
func (mdrdo *MetricDryRunDeleteOne) Where(ps ...predicate.MetricDryRun) *MetricDryRunDeleteOne {
	mdrdo.mdrd.mutation.Where(ps...)
	return mdrdo
}

// Exec executes the deletion query.
func (mdrdo *MetricDryRunDeleteOne) Exec(ctx context.Context) error {
	n, err := mdrdo.mdrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{metricdryrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mdrdo *MetricDryRunDeleteOne) ExecX(ctx context.Context) {
	if err := mdrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
