#!/bin/env node
/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/no-var-requires */

const fs = require("fs");
const path = require("path");
const glob = require("glob");
const PATTERN = "features/**/*Screen.tsx";
const DST = path.join(__dirname, "../Screens.tsx");

function gen() {
  const fd = fs.openSync(DST, "w");

  fs.writeSync(fd, "// DO NOT EDIT\n");
  fs.writeSync(
    fd,
    "// This file is automatically generated by ./scripts/genscreen.js\n"
  );
  glob(PATTERN, function (err, files) {
    if (err) {
      console.error(err);
    }
    files.forEach(function (f, i) {
      const name = f.replace(/\.tsx$/, "");
      fs.writeSync(fd, `import S${i} from './${name}';\n`);
    });

    fs.writeSync(fd, "\n");
    fs.writeSync(fd, "const Screens = [\n");
    files.forEach(function (_, i) {
      fs.writeSync(fd, `  S${i},\n`);
    });
    fs.writeSync(fd, "];\n");
    fs.writeSync(fd, "export default Screens;\n");
    fs.closeSync(fd);
  });
}

gen();
