name: CI - Expo
on:
  push:
    branches:
      - main
    paths:
      - "expo/**"
      - ".github/workflows/ci-expo.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "expo/**"
      - ".github/workflows/ci-expo.yml"

jobs:
  test-expo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: cd expo && bun install --frozen-lockfile && bun jest
      - run: cd expo && bun lint
