name: CI - Expo
on:
  push:
    branches:
      - main
    paths:
      - "expo/**"
      - ".github/workflows/ci-expo.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "expo/**"
      - ".github/workflows/ci-expo.yml"

jobs:
  test-expo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "expo/package.json"
      - run: cd expo && cp config/dev/icon.png assets/
      - run: cd expo && cp config/dev/splash.png assets/
      - run: cd expo && yarn install && yarn test
      - run: cd expo && yarn lint
