name: Expo - OTA Update Auto
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "expo/**"
      - ".github/workflows/eas-ota-update-auto.yml"

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: eas-submission
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22.3.0"
          cache: "yarn"
          cache-dependency-path: "expo/package.json"
      - uses: expo/expo-github-action@v8
        with:
          eas-version: 13.4.2
          token: ${{ secrets.EXPO_TOKEN }}
      - run: cd expo && envsubst < config/beta/secrets.json.env > config/beta/secrets.json
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
      - run: cd expo && yarn install
      - run: cd expo && ./scripts/eas.sh update --channel beta --non-interactive --auto
        env:
          HPAPP_CONFIG_NAME: beta
