name: EAS - update production
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    environment:
      name: eas
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "expo/package.json"
      - uses: expo/expo-github-action@v8
        with:
          eas-version: 13.4.2
          token: ${{ secrets.EXPO_TOKEN }}
      - run: cd expo && yarn install
      - run: cd expo && ./scripts/eas.sh update --channel prod --non-interactive --auto
        env:
          HPAPP_CONFIG_NAME: prod
