name: EAS - build
on:
  workflow_dispatch:
    inputs:
      config:
        description: "HPAPP_CONFIG_NAME set"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - beta
          - prod
      platform:
        description: "Platform to build for"
        required: true
        default: "ios"
        type: choice
        options:
          - ios
          - android
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: eas
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: expo/expo-github-action@v8
        with:
          eas-version: 5.4.0
          token: ${{ secrets.EXPO_TOKEN }}
      - run: cd expo && bun install --frozen-lockfile
      - run: cd expo && ./scripts/eas.sh build --profile ${{inputs.config}} --platform ${{inputs.platform}} --non-interactive
        env:
          HPAPP_CONFIG_NAME: ${{inputs.config}}
          HPAPP_CONFIG_PLATFORM: ${{inputs.platform}}
