name: EAS - Build Android
on:
  workflow_dispatch:
    inputs:
      dev:
        description: "HPAPP_CONFIG_NAME=dev"
        required: false
        type: boolean
        default: false
      beta:
        description: "HPAPP_CONFIG_NAME=beta"
        required: false
        type: boolean
        default: false
      prod:
        description: "HPAPP_CONFIG_NAME=prod"
        required: false
        type: boolean
        default: false
env:
  NODE_VERSION: 22.3.0
  EAS_VERSION: 13.4.2
  JAVA_VERSION: 17
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.generatematrix.outputs.target }}
    steps:
      - id: generatematrix
        run: |
          inputs='${{ toJson(github.event.inputs) }}'
          targets=()
          for key in $(echo "$inputs" | jq -r 'keys[]'); do
            if [ "$(echo "$inputs" | jq -r ".\"$key\"")" == "true" ]; then
              targets+=("$key")
            fi
          done
          targets_str=$(printf ',"%s"' "${targets[@]}")
          targets_str="[${targets_str:1}]"
          echo "target=$targets_str" >> $GITHUB_OUTPUT
  build:
    needs: generate-matrix
    strategy:
      matrix:
        target: ${{ fromJson(needs.generate-matrix.outputs.target) }}
    runs-on: ubuntu-latest
    environment:
      name: eas-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "expo/package.json"
      - uses: expo/expo-github-action@v8
        with:
          eas-version: ${{ env.EAS_VERSION }}
          token: ${{ secrets.EXPO_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
      - uses: android-actions/setup-android@v3
      - run: cd expo && rm ./config/${{ matrix.target }}/.gitignore
      - run: cd expo && rm ./.gitignore
      - run: cd expo && yarn install
      - run: cd expo && envsubst < ./.env > ./.env.local
        env:
          APP_CHECK_DEBUG_TOKEN: ${{ secrets.APP_CHECK_DEBUG_TOKEN }}
          GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
      - run: cd expo && ./scripts/eas.sh build --profile ${{ matrix.target }} --platform android --local --output ${{ github.workspace }}/expo/build/hpapp-${{ matrix.target }}.apk
        if: ${{ matrix.target == 'dev' }}
        env:
          HPAPP_CONFIG_NAME: ${{ matrix.target }}
          GOOGLE_SERVICES_INFO_PLIST: ${{ secrets.GOOGLE_SERVICES_INFO_PLIST }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - run: cd expo && ./scripts/eas.sh build --profile ${{ matrix.target }} --platform android --local --output ${{ github.workspace }}/expo/build/hpapp-${{ matrix.target }}.aab
        if: ${{ matrix.target != 'dev' }}
        env:
          HPAPP_CONFIG_NAME: ${{ matrix.target }}
          GOOGLE_SERVICES_INFO_PLIST: ${{ secrets.GOOGLE_SERVICES_INFO_PLIST }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.target == 'dev' }}
        with:
          name: hpapp-${{ matrix.target }}.apk
          path: ${{ github.workspace }}/expo/build/hpapp-${{ matrix.target }}.apk
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.target != 'dev' }}
        with:
          name: hpapp-${{ matrix.target }}.aab
          path: ${{ github.workspace }}/expo/build/hpapp-${{ matrix.target }}.aab
  submit:
    if: ${{ github.event.inputs.beta == 'true' || github.event.inputs.prod == 'true' }}
    needs: [generate-matrix, build]
    strategy:
      matrix:
        target: ${{ fromJson(needs.generate-matrix.outputs.target) }}
        exclude:
          - target: dev
    runs-on: ubuntu-latest
    environment:
      name: eas-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "expo/package.json"
      - uses: expo/expo-github-action@v8
        with:
          eas-version: ${{ env.EAS_VERSION }}
          token: ${{ secrets.EXPO_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: hpapp-${{ matrix.target }}.aab
          path: ${{ github.workspace }}/expo/build/
      - run: cd expo && yarn install
      - run: cd expo && rm ./config/${{ matrix.target }}/.gitignore
      - run: cd expo && rm ./.gitignore
      - run: cd expo && envsubst < ./config/eas.json.env > ./config/eas.json
        env:
          EAS_SUBMIT: ${{ secrets.EAS_SUBMIT }}
      - run: cd expo && envsubst < ./config/PlayStoreKey.json.env > ./config/PlayStoreKey.json
        env:
          EAS_SUBMIT: ${{ secrets.EAS_SUBMIT }}
          PLAY_STORE_KEY: ${{ secrets.PLAY_STORE_KEY }}
      - run: cd expo && ./scripts/eas.sh submit --profile ${{ matrix.target }} --platform android --non-interactive --path ${{ github.workspace }}/expo/build/hpapp-${{ matrix.target }}.aab
        if: ${{ matrix.target != 'dev' }}
        env:
          HPAPP_CONFIG_NAME: ${{ matrix.target }}
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
  upload-cloud-storage:
    if: ${{ github.event.inputs.dev == 'true' }}
    needs: [generate-matrix, build]
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment:
      name: gcp-go
    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_USER }}
      - uses: actions/download-artifact@v4
        with:
          name: hpapp-dev.apk
          path: ${{ github.workspace }}/expo/build/
      - uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: ${{ github.workspace }}/expo/build/hpapp-dev.apk
          destination: "hpapp.yssk22.dev/artifacts"
